---
- name: Basic system setup
  hosts: web
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: '*'
        state: "{{ package_state }}"
    
    - name: Create a new user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
        create_home: true
